from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import (
  PersonViewSet,
  LongTaskStartView,
  LongTaskStatusView,
  compute_experience_statistics,
  get_latest_experience_statistics,
  start_experience_statistics_task,
)


router = DefaultRouter()
router.register(r"persons", PersonViewSet, basename="person")

urlpatterns = [
  # Async long-running task endpoints
  path("long-task/", LongTaskStartView.as_view(), name="long-task-start"),
  path(
    "long-task/<uuid:task_id>/",
    LongTaskStatusView.as_view(),
    name="long-task-status",
  ),
  path("persons/experience-stats/start/", start_experience_statistics_task.as_view(), name="start-experience-stats-task"),

  path("persons/experience-stats/latest/", get_latest_experience_statistics.as_view(), name="latest-experience-statistics"),
]

# CRUD routes generated by the router
urlpatterns += router.urls
