from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import (
    PersonViewSet,
    LongTaskStartView,
    LongTaskStatusView,
)

router = DefaultRouter()
router.register(r"persons", PersonViewSet, basename="person")

urlpatterns = [
    # async long-running task endpoints
    path("long-task/", LongTaskStartView.as_view(), name="long-task-start"),
    path(
        "long-task/<uuid:task_id>/",
        LongTaskStatusView.as_view(),
        name="long-task-status",
    ),
]

# append crud routes generated by the router
urlpatterns += router.urls