# Generated by Django 4.2.7 on 2025-12-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='media_raw',
            field=models.TextField(blank=True, help_text='Números separados por vírgula para o cálculo da Média', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='desvio_raw',
            field=models.TextField(blank=True, help_text='Números separados por vírgula para o cálculo do Desvio Padrão', null=True),
        ),
    ]
