# Generated by Django 4.2.7 on 2026-01-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rating',
            field=models.IntegerField(default=800),
        ),
    ]
