# Generated by Django 4.2.7 on 2025-12-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience in their hobbies', null=True),
        ),
    ]
