# Generated by Django 4.2.7 on 2025-12-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_years_of_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_experience', models.FloatField()),
                ('std_dev_experience', models.FloatField()),
                ('count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='years_of_experience',
        ),
    ]
