# Generated by Django 4.2.7 on 2025-12-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_media_raw_person_stats_person_std_dev_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='variancia_raw',
            field=models.TextField(blank=True, default='', help_text='Insira números separados por vírgula para calcular a variância.', verbose_name='Variância (Input)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='desvio_raw',
            field=models.TextField(blank=True, default='', help_text='Insira números separados por vírgula para calcular o desvio padrão.', verbose_name='Desvio Padrão (Input)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='media_raw',
            field=models.TextField(blank=True, default='', help_text='Insira números separados por vírgula para calcular a média.', verbose_name='Média (Input)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='stats',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Estatísticas Calculadas'),
        ),
    ]
