# Generated by Django 4.2.7 on 2025-12-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_personstatistics_remove_person_years_of_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonStatistics',
        ),
        migrations.AddField(
            model_name='person',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Number of years of experience the person has on the hobby.', null=True),
        ),
    ]
