# Generated by Django 4.2.7 on 2025-12-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_experiencestatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Number of years of experience the person has on the hobby.', null=True),
        ),
    ]
